export enum ExceptionName {
  AccountAlreadyVerified = 'AccountAlreadyVerified',
  AppointmentConflict = 'AppointmentConflict',
  AppointmentCancellationFailed = 'AppointmentCancellationFailed',
  IdentifierNotFound = 'IdentifierNotFound',
  InvalidCouponCode = 'InvalidCouponCode',
  InvalidCredentials = 'InvalidCredentials',
  InvalidPayment = 'InvalidPayment',
  InvalidQuantity = 'InvalidQuantity',
  InvalidToken = 'InvalidToken',
  InventoryOutOfStock = 'InventoryOutOfStock',
  NoAppointmentSlotAvailable = 'NoAppointmentSlotAvailable',
  ProductNoAvailable = 'ProductNoAvailable',
  ResourceNotFound = 'ResourceNotFound',
  ServiceAlreadyBooked = 'ServiceAlreadyBooked',
  ServiceNotAvailable = 'ServiceNotAvailable',
  UnauthorizedAccess = 'UnauthorizedAccess',
  UserAccountNotVerified = 'UserAccountNotVerified',
  UserAlreadyRegistered = 'UserAlreadyRegistered',
  UserNotFound = 'UserNotFound',
}
