### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "identifier": "0123456789",
  "password": "newPassword123"
}

###

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "0123456789",
  "password": "newPassword123"
}

### SET TOKEN
@refreshToken = {{login.response.body.data.refreshToken}}
@accessToken = {{login.response.body.data.accessToken}}

###

# @name refresh
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### SET TOKEN
@accessToken = {{refresh.response.body.data.accessToken}}

###

### Forgot Password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "identifier": "0123456789"
}

###

### Forgot Password
POST http://localhost:3000/auth/send-verification-link
Content-Type: application/json

{
  "identifier": "0123456789"
}

###

### Reset Password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "phone": "0123456789",
  "token": "e2659a81-f5d8-4c28-a7a7-52fa30824e23",
  "newPassword": "newPassword123"
}

###

### Verify Email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "email": "john@example.com",
  "token": "bea4dba3-d06d-4d17-bf07-35e718f42f60"
}

###

### Get Authenticated User
GET http://localhost:3000/auth/me
Authorization: Bearer {{accessToken}}

###

### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer {{refreshToken}}
