### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "identifier": "john@example.com",
  "password": "newPassword123"
}

###

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "john@example.com",
  "password": "newPassword123"
}

### SET TOKEN
@refreshToken = {{login.response.body.data.refreshToken}}
# @accessToken = {{login.response.body.data.accessToken}}

###

# @name refresh
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### SET TOKEN
@accessToken = {{refresh.response.body.data.accessToken}}

###

### Forgot Password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "identifier": "john@example.com"
}

###

### Forgot Password
POST http://localhost:3000/auth/send-verification-link
Content-Type: application/json

{
  "identifier": "john@example.com"
}

###

### Reset Password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "phone": "0123456789",
  "token": "38f83c5f-a124-447d-b8ff-1573434c53b1",
  "newPassword": "newPassword123"
}

###

### Verify Email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "email": "john@example.com",
  "token": "088257ad-2968-4794-a202-f56fcadc4fee"
}

###

### Get Authenticated User
GET http://localhost:3000/auth/me
Authorization: Bearer {{accessToken}}

###

### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer {{refreshToken}}
